version: "3.7"

services:
  api:
    container_name: api
    build:
      context: ./api
    #   dockerfile: Dockerfile
    #   # args:
    #   #   - SERVER_PORT=${SERVER_PORT}
    #   #   - JWT_SECRET=${JWT_SECRET}
    #   #   - JWT_EXPIRE=${JWT_EXPIRE}
    #   #   - REDIS_HOST=${REDIS_HOST}
    #   #   - REDIS_PORT=${REDIS_PORT}
    #   #   - DATABASE_HOST=${DATABASE_HOST}
    #   #   - DATABASE_PORT=${DATABASE_PORT}
    #   #   - DATABASE_NAME=${DATABASE_NAME}
    #   #   - DATABASE_USER=${DATABASE_USER}
    #   #   - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    # environment:
    #   - SERVER_PORT:${SERVER_PORT}
    #   - JWT_SECRET:${JWT_SECRET}
    #   - JWT_EXPIRE:${JWT_EXPIRE}
    #   - REDIS_HOST:${REDIS_HOST}
    #   - REDIS_PORT=:${REDIS_PORT}
    #   - DATABASE_HOST:${DATABASE_HOST}
    #   - DATABASE_PORT:${DATABASE_PORT}
    #   - DATABASE_NAME:${DATABASE_NAME}
    #   - DATABASE_USER:${DATABASE_USER}
    #   - DATABASE_PASSWORD:${DATABASE_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./api:/app
    ports:
      - ${SERVER_PORT}:3000
      - 9229:9229
    depends_on:
      - db
      # - redis

  web_client:
    container_name: web_client
    restart: always
    build:
      context: ./web
      dockerfile: Dockerfile
    # environment:
    #   GRAPHQL: api
    volumes:
      - ./web:/app
    ports:
      - 80:3000
    depends_on:
      - api

  db:
    image: postgres:12-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: /var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./db:/var/lib/postgresql/data

  # redis:
  #   container_name: redis
  #   image: redis:6.0.9-alpine

  # pgAdmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@hello.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   depends_on:
  #     - db
  #   volumes:
  #     - /.pgadmin
  #   ports:
  #     - 5050:80
