version: "3.7"

services:
  api:
    container_name: api
    build:
      context: ./api
    env_file:
      - .env
    volumes:
      - ./api:/app
    ports:
      - ${SERVER_PORT}:3000
      - 9229:9229
    tty: true
    depends_on:
      - db
      # - redis

  web_client:
    container_name: web_client
    restart: always
    build:
      context: ./web
    env_file:
      - .env
    volumes:
      - ./web:/app
    ports:
      - 80:3000
      - 6006:6006
    depends_on:
      - api

  db:
    image: postgres:12-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: /var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./db:/var/lib/postgresql/data

  # redis:
  #   container_name: redis
  #   image: redis:6.0.9-alpine

  # pgAdmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@hello.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   depends_on:
  #     - db
  #   volumes:
  #     - /.pgadmin
  #   ports:
  #     - 5050:80
